# Generated by Django 5.0.2 on 2024-03-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('linkedId', models.IntegerField(null=True)),
                ('linkPrecedence', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(null=True)),
            ],
        ),
    ]
